[package]
name = "array_init_macro"
version = "0.1.1"
edition = "2021"
description = "Simple initialization macro for arrays."
license = "MIT"
repository = "https://github.com/ramon54321/array_init_macro.git"

[dependencies]
